// Lista de códigos de indicadores con nombres asociados
export const indicatorCodes = [
  { Code: "NY.GDP.MKTP.CD", Name: "PIB (en dólares actuales)", measurement: 'USD' },
  { Code: "NY.GDP.MKTP.KD.ZG", Name: "Tasa de crecimiento del PIB real", measurement: '%' },
  { Code: "NY.GDP.PCAP.CD", Name: "PIB per cápita (en dólares actuales)", measurement: 'USD' },
  { Code: "NE.EXP.GNFS.CD", Name: "Exportaciones de bienes y servicios (en dólares actuales)", measurement: 'USD' },
  { Code: "NE.IMP.GNFS.CD", Name: "Importaciones de bienes y servicios (en dólares actuales)", measurement: 'USD' },
  { Code: "GC.DOD.TOTL.GD.ZS", Name: "Deuda total del gobierno como porcentaje del PIB", measurement: '%' },
  { Code: "SH.XPD.CHEX.GD.ZS", Name: "Gasto en salud como porcentaje del PIB", measurement: '%' },
  { Code: "SP.POP.TOTL", Name: "Población total", measurement: 'people' },
  { Code: "SH.DYN.MORT", Name: "Tasa de mortalidad infantil (por cada 1,000 nacidos vivos)", measurement: '/1000' },
  { Code: "SE.XPD.TOTL.GD.ZS", Name: "Gasto en educación como porcentaje del PIB", measurement: '%' },
  { Code: "SE.SEC.ENRL.TC.ZS", Name: "Tasa bruta de matriculación en educación secundaria (% del grupo de edad correspondiente)", measurement: '%' },
  { Code: "SE.PRM.ENRL.TC.ZS", Name: "Tasa bruta de matriculación en educación primaria (% del grupo de edad correspondiente)", measurement: '%' },
  { Code: "SE.ADT.LITR.ZS", Name: "Tasa de alfabetización de adultos (% de personas de 15 años o más)", measurement: '%' },
  { Code: "EN.ATM.CO2E.KT", Name: "Emisiones de dióxido de carbono (miles de toneladas métricas)", measurement: 'thousand square tons' },
  { Code: "EN.POP.DNST", Name: "Densidad de población (personas por kilómetro cuadrado)", measurement: 'people/square kilometer' },
  { Code: "AG.LND.FRST.ZS", Name: "Porcentaje de área terrestre cubierta por bosques", measurement: '%' },
  { Code: "AG.PRD.FOOD.XD", Name: "Producción de alimentos (% del total)", measurement: '%' },
  { Code: "NY.GDP.PCAP.PP.CD", Name: "PIB per cápita, PPC (Paridad de Poder Adquisitivo, en dólares internacionales)", measurement: 'USD' },
  { Code: "SP.DYN.LE00.IN", Name: "Esperanza de vida al nacer (años)", measurement: 'years' },
  { Code: "SI.POV.GINI", Name: "Coeficiente de Gini, medida de desigualdad en la distribución de ingresos", measurement: '' },
  { Code: "SG.VAW.REAS.ZS", Name: "Proporción de mujeres que han sufrido violencia física o sexual por parte de una pareja íntima", measurement: '%' },
  { Code: "IT.NET.USER.ZS", Name: "Usuarios de Internet (% de la población)", measurement: '%'  },
  { Code: "IS.AIR.PSGR", Name: "Pasajeros transportados por vía aérea", measurement: 'people'  },
  { Code: "IT.CEL.SETS.P2", Name: "Suscripciones a telefonía celular (por cada 100 personas)", measurement: 'x100 people' }
];