// Lista de códigos de indicadores con nombres asociados
export const indicatorCodes = [
  { code: "NY.GDP.MKTP.CD", name: "PIB (en dólares actuales)" },
  { code: "NY.GDP.MKTP.KD.ZG", name: "Tasa de crecimiento del PIB real" },
  { code: "NY.GDP.PCAP.CD", name: "PIB per cápita (en dólares actuales)" },
  { code: "NE.EXP.GNFS.CD", name: "Exportaciones de bienes y servicios (en dólares actuales)" },
  { code: "NE.IMP.GNFS.CD", name: "Importaciones de bienes y servicios (en dólares actuales)" },
  { code: "GC.DOD.TOTL.GD.ZS", name: "Deuda total del gobierno como porcentaje del PIB" },
  { code: "SH.XPD.CHEX.GD.ZS", name: "Gasto en salud como porcentaje del PIB" },
  { code: "SP.POP.TOTL", name: "Población total" },
  { code: "SH.DYN.MORT", name: "Tasa de mortalidad infantil (por cada 1,000 nacidos vivos)" },
  { code: "SH.STA.ACSN", name: "Acceso a servicios de saneamiento básico (% de la población)" },
  { code: "SE.XPD.TOTL.GD.ZS", name: "Gasto en educación como porcentaje del PIB" },
  { code: "SE.SEC.ENRL.TC.ZS", name: "Tasa bruta de matriculación en educación secundaria (% del grupo de edad correspondiente)" },
  { code: "SE.PRM.ENRL.TC.ZS", name: "Tasa bruta de matriculación en educación primaria (% del grupo de edad correspondiente)" },
  { code: "SE.ADT.LITR.ZS", name: "Tasa de alfabetización de adultos (% de personas de 15 años o más)" },
  { code: "EN.ATM.CO2E.KT", name: "Emisiones de dióxido de carbono (miles de toneladas métricas)" },
  { code: "EN.POP.DNST", name: "Densidad de población (personas por kilómetro cuadrado)" },
  { code: "AG.LND.FRST.ZS", name: "Porcentaje de área terrestre cubierta por bosques" },
  { code: "AG.PRD.FOOD.XD", name: "Producción de alimentos (% del total)" },
  { code: "NY.GDP.PCAP.PP.CD", name: "PIB per cápita, PPC (Paridad de Poder Adquisitivo, en dólares internacionales)" },
  { code: "SP.DYN.LE00.IN", name: "Esperanza de vida al nacer (años)" },
  { code: "SI.POV.GINI", name: "Coeficiente de Gini, medida de desigualdad en la distribución de ingresos" },
  { code: "SG.VAW.REAS.ZS", name: "Proporción de mujeres que han sufrido violencia física o sexual por parte de una pareja íntima" },
  { code: "IT.NET.USER.ZS", name: "Usuarios de Internet (% de la población)" },
  { code: "IS.AIR.PSGR", name: "Pasajeros transportados por vía aérea" },
  { code: "IS.ROD.PAVE.ZS", name: "Porcentaje de carreteras pavimentadas" },
  { code: "IT.CEL.SETS.P2", name: "Suscripciones a telefonía celular (por cada 100 personas)" }
];